/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rs_java_RS_Native */

#ifndef _Included_rs_java_RS_Native
#define _Included_rs_java_RS_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rs_java_RS_Native
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_rs_1java_RS_1Native_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     rs_java_RS_Native
 * Method:    fin
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_rs_1java_RS_1Native_fin
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     rs_java_RS_Native
 * Method:    encode
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_rs_1java_RS_1Native_encode
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     rs_java_RS_Native
 * Method:    decode
 * Signature: (I[I[I)V
 */
JNIEXPORT void JNICALL Java_rs_1java_RS_1Native_decode
  (JNIEnv *, jobject, jint, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
